"""Add room_number and teacher to classrooms

Revision ID: 0bde43b85900
Revises: 94b76986b798
Create Date: 2025-11-30 14:13:21.409141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bde43b85900'
down_revision: Union[str, None] = '94b76986b798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Fix absences constraints
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_constraint('uix_aide_date', type_='unique')
        batch_op.create_unique_constraint('uq_absence_aide_date', ['aide_id', 'date'])
    
    op.create_index('idx_absences_aide_date', 'absences', ['aide_id', 'date'], unique=True)
    op.create_index('idx_absences_date', 'absences', ['date'], unique=False)
    
    # Fix assignments indexes
    op.drop_index('idx_assignments_recurring_series', table_name='assignments')
    op.drop_index('ix_assignments_collision', table_name='assignments')
    op.drop_index('ix_assignments_task', table_name='assignments')
    op.create_index('idx_assignments_aide_date_time', 'assignments', ['aide_id', 'date', 'start_time'], unique=False)
    op.create_index('idx_assignments_date', 'assignments', ['date'], unique=False)
    op.create_index('idx_assignments_status_date', 'assignments', ['status', 'date', 'start_time'], unique=False)
    op.create_index('idx_assignments_task_id', 'assignments', ['task_id'], unique=False)
    op.create_index(op.f('ix_assignments_recurring_series_id'), 'assignments', ['recurring_series_id'], unique=False)
    op.create_index(op.f('ix_assignments_task_id'), 'assignments', ['task_id'], unique=False)
    
    # Fix availability constraints
    op.drop_index('ix_availability_aide_weekday', table_name='availability')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('uix_aide_weekday_time', type_='unique')
        batch_op.create_unique_constraint('uq_availability_aide_day_time', ['aide_id', 'weekday', 'start_time'])

    op.create_index('idx_availability_aide_weekday', 'availability', ['aide_id', 'weekday'], unique=False)
    
    # Fix classrooms indexes
    op.create_index('idx_classrooms_name', 'classrooms', ['name'], unique=True)
    op.create_index(op.f('ix_classrooms_name'), 'classrooms', ['name'], unique=True)
    
    # Fix recurring_series indexes
    op.create_index(op.f('ix_recurring_series_task_id'), 'recurring_series', ['task_id'], unique=False)
    
    # Fix requests indexes
    op.drop_index('ix_requests_created', table_name='requests')
    op.create_index('idx_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_requests_status', 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    
    # Fix tasks indexes
    op.create_index('idx_tasks_category', 'tasks', ['category'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    
    # Fix teacher_aides indexes
    op.create_index('idx_teacher_aides_name', 'teacher_aides', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teacher_aides_name', table_name='teacher_aides')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_category', table_name='tasks')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_index('idx_requests_status', table_name='requests')
    op.drop_index('idx_requests_created_at', table_name='requests')
    op.create_index('ix_requests_created', 'requests', ['created_at'], unique=False)
    op.drop_index(op.f('ix_recurring_series_task_id'), table_name='recurring_series')
    op.drop_index(op.f('ix_classrooms_name'), table_name='classrooms')
    op.drop_index('idx_classrooms_name', table_name='classrooms')
    
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('uq_availability_aide_day_time', type_='unique')
        batch_op.create_unique_constraint('uix_aide_weekday_time', ['aide_id', 'weekday', 'start_time'])
        
    op.drop_index('idx_availability_aide_weekday', table_name='availability')
    op.create_index('ix_availability_aide_weekday', 'availability', ['aide_id', 'weekday'], unique=False)
    
    op.drop_index(op.f('ix_assignments_task_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_recurring_series_id'), table_name='assignments')
    op.drop_index('idx_assignments_task_id', table_name='assignments')
    op.drop_index('idx_assignments_status_date', table_name='assignments')
    op.drop_index('idx_assignments_date', table_name='assignments')
    op.drop_index('idx_assignments_aide_date_time', table_name='assignments')
    op.create_index('ix_assignments_task', 'assignments', ['task_id'], unique=False)
    op.create_index('ix_assignments_collision', 'assignments', ['aide_id', 'date', 'start_time'], unique=False)
    op.create_index('idx_assignments_recurring_series', 'assignments', ['recurring_series_id'], unique=False)
    
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_absence_aide_date', type_='unique')
        batch_op.create_unique_constraint('uix_aide_date', ['aide_id', 'date'])

    op.drop_index('idx_absences_date', table_name='absences')
    op.drop_index('idx_absences_aide_date', table_name='absences')
    # ### end Alembic commands ###
