"""Add colour_hex to classrooms

Revision ID: 789d74da06c5
Revises: 004_rename_qualifications_to_details
Create Date: 2025-12-28 18:53:30.101761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789d74da06c5'
down_revision: Union[str, None] = '004_rename_qualifications_to_details'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assignments_original_aide', table_name='assignments')
    op.drop_index('idx_assignments_relief_pool', table_name='assignments')
    op.create_index(op.f('ix_assignments_original_aide_id'), 'assignments', ['original_aide_id'], unique=False)
    op.add_column('classrooms', sa.Column('colour_hex', sa.String(length=7), server_default='#1976d2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'colour_hex')
    op.drop_index(op.f('ix_assignments_original_aide_id'), table_name='assignments')
    op.create_index('idx_assignments_relief_pool', 'assignments', ['status', 'date'], unique=False)
    op.create_index('idx_assignments_original_aide', 'assignments', ['original_aide_id'], unique=False)
    # ### end Alembic commands ###



